---
jobs:
  include:
    - stage: test
      services:
        - docker
      install:
        - cp hc/app/config/local_settings.py.example hc/app/config/local_settings.py
        - cp nginx/config/hc.conf.example nginx/config/hc.conf
        - cp hc/hc.env.example hc/hc.env
        - cp db/db.env.example db/db.env
      script: docker-compose up -d && sleep 30 && curl -sfL http://localhost:6863 | grep -q 'Monitor and Get Notified When Your Cron Jobs Fail.'
