---
version: '3'
services:
  hc-app:
    build: ./hc/app
    volumes:
      - ./hc/app/config:/usr/src/config:ro
      - static_files:/usr/src/app/static-collected
    env_file: hc/hc.env
    restart: always
    depends_on:
      - db
  # hc-alerts:
  #   build: ./hc/alerts
  #   volumes:
  #     - ./hc/app/config:/usr/src/config:ro
  #   env_file: hc/hc.env
  #   restart: always
  #   depends_on:
  #     - db
  nginx:
    image: nginx:1.13
    ports:
      - "6863:6863"
    restart: always
    volumes:
      - static_files:/static:ro
      - ./nginx/config/:/etc/nginx/conf.d/:ro
    depends_on:
      - hc-app
  # cleanup-worker:
  # jobber
  db:
    image: postgres:10.3
    env_file: db/db.env
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
  # backup:

volumes:
  static_files:
  db:
