#!/usr/bin/with-contenv sh
# shellcheck shell=sh

NUM_CORES=$(grep -c ^processor /proc/cpuinfo)
# as per the gunicron docs
WORKERS_COUNT=$((2 * NUM_CORES + 1))

exec s6-setuidgid nobody gunicorn hc.wsgi --bind 0.0.0.0:8000 --workers $WORKERS_COUNT
