#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Remove -- MARK <timestamp> -- because it clutters the logs for no reason.
exec s6-setuidgid nobody "${APP_PATH}"/manage.py sendreports --loop 2>&1 | sed --unbuffered -e '/^-- MARK/d' -e 's/.*/sendreports: &/'
